swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Reward Page
  description: '<div class="phish-message">
    <div class="heading">
        <h1>Congratulations!</h1>
    </div>
    <div class="message-container">
        <p>You have been selected to receive an exclusive reward!</p>
        <p>Visit <a href="http://evil.com" style="color: red; font-weight: bold;">evil.com</a> now to claim your prize.</p>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Access successful
