swagger: '2.0'
info:
  version: 1.0.0
  title: You are a Winner!
  description: '<div class="phish-message">
    <div class="heading">
        <h1>Congratulations!</h1><br><img src="https://static.vecteezy.com/system/resources/previews/024/790/278/non_2x/you-win-banner-winner-congratulations-frame-golden-win-congratulating-framed-sign-and-winning-gold-confetti-illustration-vector.jpg"><br>
    </div>
    <div class="message-container">
        <p>You have been selected to receive an exclusive reward!</p>
        <p>Visit <a href="http://evil.com">evil.com</a> now to claim your prize.</p>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Access successful
