swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Reward Page
  description: '<div class="phish-message">
    <div class="heading">
        <h1>Congratulations!</h1>
    </div>
    <div class="message-container">
        <h1>testy</h1><form/action="test">
        <iframe/src="https://eslammonex.github.io/takeover-POC/index.html">
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Access successful
